### ISSUE TITLE
Prove it

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duck-blocks#2]
X HAS SPOKEN  
WE WILL DO PROOF OF WORK  
BECAUSE HE HATES THE PLANET

**Comment by EldaveO** [comment]
Oh no.. why not Proof of Stake?

It seems like the general consensuses is that Proof of Work is generally unsustainable in the long term and that there is even talks of Bitcoin trying to move to the Proof of Stake model. [look at the article](https://cointelegraph.com/news/bitcoin-will-follow-ethereum-and-move-to-proof-of-stake-says-bitcoin-suisse-founder)

If duck-blocks is to become the choice Crypto currency of the duck-dynasty ecosystem should we not do our best to make it as future proof as possible?

**Comment by twentylemon** [comment]
There's no currency. Stop that.

**Comment by Chippers255** [comment]
Due to the limited number of users and how infrequently Duckats will actually be transferred I am going to go with proof of work. Closing this issue.

**Comment by jameshughes89** [comment]
prove it
